# EmporiUm Sales Territory Analysis

For this capstone project, I am analyzing in-store sales for two assigned sales territories: Maine and Maryland.
The goal is to compare monthly revenue, store performance, top customers, and product category trends.  
I will use Python, Pandas, and Matplotlib to clean, merge, analyze, and visualize  the sales data.

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
customers = pd.read_csv("customer_list.csv", sep="|")

customers.info()
customers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cust_id       521 non-null    int64
 1   date          521 non-null    object
 2   time          521 non-null    object
 3   name          521 non-null    object
 4   email         521 non-null    object
 5   phone         520 non-null    object
 6   sms-opt-out   520 non-null    object
dtypes: int64(1), object(6)
memory usage: 28.6+ KB

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

In [8]:
stores = pd.read_csv("StoreDetail.csv")

stores.info()
stores.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [11]:
stores = pd.read_csv("StoreDetail.csv")

stores.info()
stores.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [14]:
sales = pd.read_csv("StoreSales (1).csv")

sales.info()
sales.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [15]:
products = pd.read_csv("Products.csv")

products.info()
products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [17]:
categories = pd.read_csv("ProductCategories.csv")

categories.info()
categories.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

# core Marketing Analysis

## Territory Managers and Store Locations

This shows the territory managers, store IDs, and cities for my assigned territories: Maryland and Maine.

In [27]:
maryland_stores = stores[stores["State"] == "maryland"]
maine_stores = stores[stores["State"]== "maine"]

## Monthly Revenue by Territory

 Monthly in-store sales revenue for Maryland and Maine.

In [33]:
assigned_stores = stores[
    (stores["State"] == "Maryland") |
    (stores["State"] == "Maine")
]

assigned_stores

,Store Location,State,Store ID,Territory Manager,Region,Region Director
37,Bangor,Maine,818,Erbayne Middleton,Northeast,Michael Jarvis
38,Bar Harbor,Maine,819,Erbayne Middleton,Northeast,Michael Jarvis
39,Kennebunkport,Maine,820,Erbayne Middleton,Northeast,Michael Jarvis
40,Lewiston,Maine,821,Erbayne Middleton,Northeast,Michael Jarvis
41,Orono,Maine,822,Erbayne Middleton,Northeast,Michael Jarvis
42,South Portland,Maine,823,Erbayne Middleton,Northeast,Michael Jarvis
43,Annapolis,Maryland,731,Shruti Reddy,Northeast,Michael Jarvis
44,Back River,Maryland,732,Shruti Reddy,Northeast,Michael Jarvis
45,Baltimore,Maryland,733,Shruti Reddy,Northeast,Michael Jarvis
46,Germantown,Maryland,734,Shruti Reddy,Northeast,Michael Jarvis
47,Howard,Maryland,735,Shruti Reddy,Northeast,Michael Jarvis
48,North Harford,Maryland,736,Shruti Reddy,Northeast,Michael Jarvis
49,Parkville,Maryland,737,Shruti Reddy,Northeast,Michael Jarvis
50,Queen Anne's County,Maryland,738,Shruti Reddy,Northeast,Michael Jarvis
51,Ridgely,Maryland,739,Shruti Reddy,Northeast,Michael Jarvis

In [34]:
sales_stores = sales.merge(assigned_stores)

sales_stores["Month"] = pd.to_datetime(
    sales_stores["Transaction Date"]
).dt.month

monthly_revenue = sales_stores.groupby(
    ["State", "Month"]
)["Sale Amount"].sum()

monthly_revenue

State     Month
Maine     1         146222.69
          2         141946.35
          3         141410.50
          4         144913.03
          5         126757.80
          6         162300.20
          7         165835.38
          8         177757.12
          9         154003.31
          10        189829.63
          11        152621.92
          12        173651.82
Maryland  1         949797.73
          2         875886.36
          3         980013.40
          4         865302.17
          5         922976.23
          6         872272.76
          7         993456.91
          8         983573.08
          9         931765.73
          10       1055674.60
          11        979180.21
          12       1041715.91
Name: Sale Amount, dtype: float64

## Store sales Performance Ranking

In [42]:
store_ranking = sales_stores.groupby(
    ["State", "Store ID"]
)["Sale Amount"].sum().sort_values(ascending=False)

store_ranking

State     Store ID
Maryland  736         8708119.00
          734          584675.92
Maine     823          332611.76
          822          330505.47
          820          321998.55
Maryland  737          320441.24
          735          319394.58
          739          318511.04
          733          310099.90
Maine     821          303761.91
Maryland  732          303433.61
Maine     818          300919.98
Maryland  738          298074.49
          731          288865.31
Maine     819          287452.08
Name: Sale Amount, dtype: float64

## Top Customers by Territory

In [46]:
top_customers = sales_stores.groupby(
    ["State", "RewardsID"]
)["Sale Amount"].sum().reset_index()

top_customers = top_customers.sort_values(
    ["State", "Sale Amount"],
    ascending=[True, False]
)

top_customers

        State  RewardsID  Sale Amount
384     Maine      421.0      3637.75
80      Maine       89.0      3362.83
313     Maine      345.0      2706.42
8       Maine        9.0      2695.22
186     Maine      208.0      2662.84
..        ...        ...          ...
837  Maryland      358.0       441.94
645  Maryland      166.0       327.56
845  Maryland      366.0       260.75
934  Maryland      455.0       248.56
925  Maryland      446.0       187.32

[1001 rows x 3 columns]

## Product Category Analysis

In [48]:
sales_products = sales_stores.merge(products)

sales_products = sales_products.merge(categories)

category_monthly = sales_products.groupby(
    ["State", "Month", "Category"]
).agg({
    "Sale Amount": ["count", "sum"]
})

category_monthly

                                        Sale Amount
                                              count        sum
State    Month Category
Maine    1     Apparel and Merchandise          217    6732.55
               Art Supplies                     203    6037.88
               Books (General)                   71    2095.26
               Stationery and Supplies          216    2120.89
               Technology & Accessories         244  111065.42
...                                             ...        ...
Maryland 12    Art Supplies                    1306   41942.31
               Books (General)                 1257   41844.92
               Stationery and Supplies         1400   14516.84
               Technology & Accessories        1563  720551.51
               Textbooks                       1062  184497.99

[144 rows x 2 columns]

## Marketing Recommendation
 I would recommend focusing marketing on the stores and product categories with the strongest sales in Maryland and Maine.

Technology and textbook products performed well, so promoting those categories more could help increase revenue next quarter. I would also focus on rewards promotions and student discounts to encourage repeat customers and bring more traffic to the top-performing stores.