# Bonus Capstone Analysis

Filtering,sorting and Exploration

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
customers = pd.read_csv("customer_list.csv", sep="|")
stores = pd.read_csv("StoreDetail.csv")
sales = pd.read_csv("StoreSales (1).csv")
products = pd.read_csv("Products.csv")
categories = pd.read_csv("ProductCategories.csv")

In [29]:
sales["Transaction Date"] = pd.to_datetime(
    sales["Transaction Date"]
)

assigned_stores = stores[
    (stores["State"] == "Maryland") |
    (stores["State"] == "Maine")
]

sales_stores = sales.merge(assigned_stores, on="Store ID")

1. Create a list of all transactions from January 2024, sorted by sale amount from highest to lowest.
Which transactions had a sale amount greater than $500?

In [30]:
january_2024 = sales[
    (sales["Transaction Date"].dt.year == 2024) &
    (sales["Transaction Date"].dt.month == 1)
]

january_2024 = january_2024.sort_values(
    "Sale Amount",
    ascending=False
)

january_2024

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139643       2024-01-31       736        NaN   105444-S          2.4
133337       2024-01-01       901      324.0   105402-S          2.4
138904       2024-01-27       850        NaN   105611-S          2.4
136726       2024-01-17       739        NaN   105444-S          2.4
138912       2024-01-27       853        NaN   105821-S          2.4

[6654 rows x 5 columns]

In [31]:
january_2024[
    january_2024["Sale Amount"] > 500
]

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139274       2024-01-29       815        NaN  105262-IT        603.5
139391       2024-01-30       718        NaN  105262-IT        603.5
136360       2024-01-15       847        NaN  105262-IT        603.5
134154       2024-01-05       825        NaN  105262-IT        603.5
136218       2024-01-15       728        NaN  105262-IT        603.5

[497 rows x 5 columns]

2. Find all products whose product number begins with 10525. What category and subcategory do they
belong to?

In [32]:
products_10525 = products[
    products["Prod Num"].astype(str).str.startswith("10525")
]

products_10525

     Prod Num                         Product  CategoryID SubcategoryID
2   105250-IT                      Realme Pad         120       120-tab
3   105251-IT              Lenovo Tab P12 Pro         120       120-tab
4   105252-IT         Microsoft Surface Pro 9         120       120-tab
5   105253-IT  Apple iPad Pro (12.9-inch, M2)         120       120-tab
6   105254-IT                 Chuwi HiPad Max         120       120-tab
7   105255-IT           Lenovo Yoga Smart Tab         120       120-tab
8   105256-IT     ASUS Vivobook 13 Slate OLED         120       120-tab
9   105257-IT     Samsung Galaxy Tab S9 Ultra         120       120-tab
10  105258-IT      Apple iPad Air (10.9-inch)         120       120-tab
11  105259-IT                 Teclast T40 Pro         120       120-tab

3. Which stores in your assigned territories had at least one transaction with a sale amount over
$1,000? How many such transactions did each store have?

In [33]:
transactions_1000 = sales_stores[
    sales_stores["Sale Amount"] > 1000
]

transactions_1000.groupby(
    ["State", "Store ID"]
)["Sale Amount"].count()

State     Store ID
Maine     818           93
          819           70
          820           93
          821           82
          822           85
          823           97
Maryland  731           72
          732           84
          733           89
          734          153
          735           86
          736         2241
          737           91
          738           79
          739           90
Name: Sale Amount, dtype: int64